services:
  - type: web
    name: lunch
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: TURSO_URL
        sync: false
      - key: TURSO_TOKEN
        sync: false
